# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10539f7f704caee7b408aefde4d1f3380621911994cb7298b6a0a30a9e5a835baeabe866624ed0f4d3e2d480a0eb2b5794d5580285b3191f61455041b4f5d039

test:
  secret_key_base: 64e9bd58e21d294a2965c13e3a65fba533574e945b1ea9a154c62db385a32244f45223a89018fec4da95665cdccf409bc1d78b98da52228a8a2d05229f2592ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
